### ISSUE TITLE
Prevent identifying "protein" entities

### ISSUE THREAD

**Issue by banana-Z** [jbjorne/TEES#30]
Dear author,

I'm extracting the relations between drug and clinical entity (ADE/dosage/frequency/form/duration/route/strength/reason). But the preprocess.py result (.xml) shows the entity type of "Protein" is also identified, shown as follows:
<img width="1081" alt="screen shot 2018-10-02 at 3 37 54 pm" src="https://user-images.githubusercontent.com/28758755/46331046-4b267280-c659-11e8-95d8-5f6b6ff1f61e.png">

How to not identity "Protein" type in text files?
So the structure.txt from trained model will not show "ENTITY Protein".
<img width="1097" alt="screen shot 2018-10-02 at 3 41 49 pm" src="https://user-images.githubusercontent.com/28758755/46331148-c2f49d00-c659-11e8-9bc4-0a00cd2f1723.png">

**Comment by jbjorne** [comment]
The BANNER program is run as part of preprocess.py in order to generate the "Protein" entities which many of the models require for event extraction. In order to not have these entities, please run the preprocessing pipeline (https://github.com/jbjorne/TEES/wiki/The-Preprocessor) without the BANNER step.

**Comment by banana-Z** [comment]
Thanks for your help, it worked in the computing project.
